image: ubuntu:latest

stages:
  - test
  - build

before_script:
    - apt update -y
    - apt install docker.io -y
#   - cd $GOPATH/src
#   - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
#   - cd gitlab.com/$CI_PROJECT_NAMESPACE
#   - ln -s $CI_PROJECT_DIR
#   - cd $CI_PROJECT_NAME
#   - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
#   - dep ensure -vendor-only
    - cd ..
    - ls
    - pwd

# lint_code:
#   stage: test
#   script:
#     # - make lint

# unit_tests:
#   stage: test
#   script:
    # - make test

build:
  stage: build
  script:
    - docker build awesome
