runmode: debug               # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: main              # API Server的名字
url: http://127.0.0.1:2019   # pingServer函数请求的API服务器的ip:port
max_ping_count: 5           # pingServer函数try的次数
#jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
#tls:
#  addr: :8081
#  cert: conf/server.crt
#  key: conf/server.key
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/golang.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: acke_test
  addr: 106.12.130.179:3306
  username: root
  password: root

docker_db:
  name: acke_test
  addr: 106.12.130.179:3307
  username: root
  password: root
  max_idle_connection: 10
  max_open_connection: 100

company:
  name: tenghui